spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 100MB
logging:
  config: classpath:logback-spring.xml



